# Generated by Django 2.1.7 on 2019-03-30 00:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0002_auto_20190329_1847'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffschedule',
            name='staffID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staffUserID', to=settings.AUTH_USER_MODEL),
        ),
    ]
