# Generated by Django 2.1.7 on 2019-03-29 23:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArrivalTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.TimeField()),
                ('licenseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userID', to='user.User')),
            ],
        ),
        migrations.CreateModel(
            name='PhilDay',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDay', models.DateField()),
                ('startTime', models.TimeField()),
                ('endTime', models.TimeField()),
                ('endDay', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='arrivaltime',
            name='philsDay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dayPhils', to='timing.PhilDay'),
        ),
    ]
