# Generated by Django 2.1.7 on 2019-04-01 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_ban'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ban',
            name='licenseID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='licenseIDUser', to=settings.AUTH_USER_MODEL),
        ),
    ]
